### Créé un ustilisateur

POST localhost:8080/users
Content-Type: application/json

{
    "email": "christopheEmail@gmail.com",
    "password": "ChPassword@1"
}


### Récupère un utilisateur par son email et mot de passe
POST localhost:8080/users/user
Content-Type: application/json

{
    "email" : "christopheNewEmail@gmail.com",
    "password" : "CHpassword@1"
}



### test du changement de l'email. Doit retourner l'utilisateur modifié
PUT localhost:8080/users/user
Content-Type: application/json

{
  "id" : "20da5de9-fa12-4221-82ef-f23b3083f070",
  "email": "christopheNewEmail@gmail.com"
}

### test du changement d'un email invalide. Doit retourner 'Email invalide.'
PUT localhost:8080/users/user
Content-Type: application/json

{
  "id" : "20da5de9-fa12-4221-82ef-f23b3083f070",
  "email": "christopheNewEmailgmail.com"
}

### test du changement d'un email qui existe déjà. Doit retourner 'Email déjà utilisée.'
PUT localhost:8080/users/user
Content-Type: application/json

{
  "id" : "20da5de9-fa12-4221-82ef-f23b3083f070",
  "email": "christopheNewEmail@gmail.com"
}

### test du changement du password. Doit retourné l'utilisateur modifié
PUT localhost:8080/users/user
Content-Type: application/json

{
  "id" : "20da5de9-fa12-4221-82ef-f23b3083f070",
  "password": "CHpassword@2"
}

### test du changement d'un mauvais password. Doit retourné 'Password invalide'
PUT localhost:8080/users/user
Content-Type: application/json

{
  "id" : "20da5de9-fa12-4221-82ef-f23b3083f070",
  "password": "CHpassword@"
}


### test du changement de l'email et du password. Doit retourné l'utilisateur modifié
PUT localhost:8080/users/user
Content-Type: application/json

{
  "id" : "20da5de9-fa12-4221-82ef-f23b3083f070",
  "email" : "christopheNewEmailAndPassword@gmail.com",
  "password": "CHpassword@2"
}


### test de la suppresion d'un utilisateur. Doit retourné 'utilisateur supprimé.'
DELETE localhost:8080/users/user
Content-Type: application/json

{
  "id": "20da5de9-fa12-4221-82ef-f23b3083f070"
}

### test de la suppresion d'un utilisateur non valide. Doit retourné 'Id invalide.'
DELETE localhost:8080/users/user
Content-Type: application/json

{
  "id": "c23a126b-1811-404b-b0cb-7a5eeb8cd1a1"
}